version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_COMMUNITY_PACKAGE_ALLOW_LIST=true
      - N8N_EDITOR_BASE_URL=https://${NGROK_DOMAIN}
      - WEBHOOK_URL=https://${NGROK_DOMAIN}
      - WEBHOOK_TUNNEL_URL=https://${NGROK_DOMAIN}
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - TZ=Etc/UTC
    restart: always

