version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-demo-test
    ports:
      - "5678:5678"
    restart: always
    environment:
      - N8N_COMMUNITY_PACKAGE_ALLOW_LIST=true
      - N8N_EDITOR_BASE_URL=https://peacock-golden-swift.ngrok-free.app
      - WEBHOOK_URL=https://peacock-golden-swift.ngrok-free.app
      - WEBHOOK_TUNNEL_URL=https://peacock-golden-swift.ngrok-free.app
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    volumes:
      - ./n8n_data:/home/node/.n8n  # Local directory bind to store data persistently
